### ISSUE TITLE
Problem with ll friends and ll manage

### ISSUE THREAD

**Issue by radiodrag** [SpatiumPrinceps/LandLord#5] opened 2017-06-24 00:35 UTC
The problem with ll friends is on spigot (I'm nicecube on spigot), i think you've seen it, and the ll manage throw that error:
`[20:37:21] [Server thread/INFO]: NekoSenpaiii issued server command: /ll manage
[20:37:21] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'll' in plugin Landlord v1.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
	at com.jcdesimp.landlord.landManagement.LandManagerView.updateUIData(LandManagerView.java:93) ~[?:?]
	at com.jcdesimp.landlord.landManagement.LandManagerView.<init>(LandManagerView.java:49) ~[?:?]
	at com.jcdesimp.landlord.landManagement.ViewManager.activateView(ViewManager.java:23) ~[?:?]
	at com.jcdesimp.landlord.commands.Manage.execute(Manage.java:64) ~[?:?]
	at com.jcdesimp.landlord.LandlordCommandExecutor.onCommand(LandlordCommandExecutor.java:65) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12-R0.1-SNAPSHOT.jar:git-Spigot-cd6ba67-f7d14f1]
	... 15 more`

**Comment by SpatiumPrinceps** [comment] 2017-06-24 08:58
ll friends should be fixed. this one seem to cause more headaches. What are you doing that this error occures?

**Comment by radiodrag** [comment] 2017-06-28 04:16
Only doing /ll manage

**Comment by SpatiumPrinceps** [comment] 2017-06-28 15:39
Are you using the latest build from my build Server? There used to be ( in an ancient build) some problems concernig this issue

**Comment by SpatiumPrinceps** [comment] 2017-07-14 21:44
Is this still a issue? I honestly cant reproduce this

**Comment by radiodrag** [comment] 2017-07-17 01:19
yes, there's still an issue, i'm on build 40 right now

**Comment by SpatiumPrinceps** [comment] 2017-07-17 11:57
Ah yes. I remember this little thingy when I partially redid the manage cmd. There is a huge flaw in this code, which I wont fix right now, because its very deep anchored inside the plugin and would require a massive overhowl. 
If you are renaming the ll manage stuff back to the default it should work. There where just two values which need to be the same, but dont remember which. 
Has something todo with the flags, thats why its so deeply anchored :(

I started a rewrite yesterday, better said started to write a extensive api in order to allow a very fast and easy rewrite.

**Comment by radiodrag** [comment] 2017-07-19 18:40
I saw the landlord-V2, should i get this one instead of the "V1"?

**Comment by SpatiumPrinceps** [comment] 2017-07-19 18:41
Have you read my post on Spigot? It is basically said a rewritten beta

**Comment by radiodrag** [comment] 2017-07-19 18:47
Oh, yeah, sorry! We're 3 people on the same spigot account (server owner, me and another admin, same server), Like he said, we'll test this the soonest possible, probably this weekend

**Comment by SpatiumPrinceps** [comment] 2017-07-19 18:56
sure, just wondered a bit :D 
Its already very stable in my opinion. And the codebase is something you can work with :+1:  
Feel free to tell me what you are missing, I will implement probably everything if its possibly

**Comment by radiodrag** [comment] 2017-07-20 02:51
not sur if it must be posted here, but is it possible to manage the greet and farewell message on all the owned lands?

**Comment by SpatiumPrinceps** [comment] 2017-07-20 08:12
Yes, every single land can have a custom farewell/greet

**Comment by radiodrag** [comment] 2017-07-22 03:43
yes batch editing, greet and farewell messages mostly, some players could abuse this and put a different message on every lands they have

**Comment by SpatiumPrinceps** [comment] 2017-07-22 08:54
Why is it abusing? The message will only be displayed if you enter/leave to a land with a different owner

**Comment by radiodrag** [comment] 2017-07-23 05:32
if someone buy lands and put different messages on every lands he owns, when we go on his lands we will have tons of differents land messages spamming in the chat

**Comment by SpatiumPrinceps** [comment] 2017-07-23 07:17
I'm almost certain, that the message will only be displayed when you enter a region which has not the same rights for you. 
If not you should contact the world guard guy. 
Think I even tested this xD

**Comment by radiodrag** [comment] 2017-07-23 17:34
I still have the issue, looked at worldguard config, no option for that, i'm on the newest worldguard.I've set 4 different messages on 4 differents lands and that's the result.
 [https://lh3.googleusercontent.com/-FcjQl08I-Ao/WXTd1D5yFnI/AAAAAAAAG1Y/bsB2tgh7TL8yzCBkE3yAxzXq6yQKDJ0hgCHMYCw/s0/javaw_2017-07-23_13-33-08.png](url)

**Comment by SpatiumPrinceps** [comment] 2017-07-23 18:11
The Url leads me nowhere. I think i tested this earlier today, and it worked as intended? Anyways, there is nothing I could do about this, since its worldguard

**Comment by SpatiumPrinceps** [comment] 2017-07-23 18:42
Yea, but I can reproduce it.
There is (no) way I could modify worldguard from my plugin without touching wg itsself. 

Probably I can do something, but its veeeery hacky and very complicated.

**Closed by SpatiumPrinceps** 2017-07-23 18:42 UTC
Labels: major

**Comment by radiodrag** [comment] 2017-07-24 03:55
you need to copy/paste the link, i think github block links outside of itself or something like that

**Comment by SpatiumPrinceps** [comment] 2017-07-24 16:35
got it fixed.
