### ISSUE TITLE
Error at /ll

### ISSUE THREAD

**Issue by download042** [SpatiumPrinceps/LandLord#62] opened 2018-03-05 12:41 UTC
Hi!

I just installed LandLord plugin.
If i type /LL i got this error: https://pastebin.com/Cpw1Atmg

LandLord: b144
WorldGuard: 6.1.3
ProtocolLib: 4.3.0
Vault: 1.5.6-b49
Spigot: the latest 1.11.2
No PAPI and no LandLord-DynMap installed.

Thank you in advance for your answer!

**Comment by download042** [comment] 2018-03-05 12:47
![image](https://user-images.githubusercontent.com/13710574/36975850-bf7cd7de-207b-11e8-8255-ca05d6f0fdb3.png)

And i got on every command this message..

**Comment by LinzN** [comment] 2018-03-05 12:56
Are you using spigot or craftbukkit?

**Comment by download042** [comment] 2018-03-05 12:57
Spigot

**Comment by download042** [comment] 2018-03-05 12:57
"This server is running CraftBukkit version git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)"

**Comment by SpatiumPrinceps** [comment] 2018-03-14 14:26
Should be fixed in [b153](http://ci.princeps.biz:7777/job/LandLord/). 
At least I was not able to reproduce this issue any longer. 

Please let me know, if you notice something else!

**Closed by SpatiumPrinceps** 2018-03-14 14:26 UTC
Labels: under investigation
